### ISSUE TITLE
errors running script under windows

### ISSUE THREAD

**Issue by different-thinking** [jademind/slack-files-download#2]
The script is what I'm looking for! Thanks.

I want to run it under phyton 3.11 in windows and get the following errors:

Traceback (most recent call last):------------------------------] 0.0% ...processing channels
  File "C:\Users\robert\Downloads\slack-files-download.py", line 102, in <module>
    process_directories(args.directory, directories, output=args.out)
  File "C:\Users\robert\Downloads\slack-files-download.py", line 51, in process_directories
    data = json.load(open(file_path))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\robert\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^^^
  File "C:\Users\robert\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 35062: character maps to <undefined>

Would be happy if you can help.

**Comment by simonratner** [comment]
[Line 51](https://github.com/jademind/slack-files-download/blob/e799bb556cc2cd4460bac8571865b4b3fcf29014/slack-files-download.py#L51), specify `utf8` encoding for the open call (defaults to `cp1252` on en-US Windows otherwise):
```diff
- data = json.load(open(file_path))
+ data = json.load(open(file_path, encoding='utf8'))
```
